// <auto-generated />
using System;
using GalaxyMiReto.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GalaxyMiReto.Migrations
{
    [DbContext(typeof(DeveloperDbContext))]
    [Migration("20200825021505_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GalaxyMiReto.GalaxyMiReto.Models.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContratoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContractWorker")
                        .IsRequired()
                        .HasColumnName("ContractWorker")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<int>("ContratoNumero")
                        .HasColumnName("ContratoNumero")
                        .HasColumnType("int")
                        .HasMaxLength(5);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnName("EntityName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FinalDate")
                        .IsRequired()
                        .HasColumnName("FinalDate")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("InitialDate")
                        .IsRequired()
                        .HasColumnName("InitialDate")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("ContratoId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("GalaxyMiReto.GalaxyMiReto.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnName("Age")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("DateBirth")
                        .IsRequired()
                        .HasColumnName("DateBirth")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasColumnName("FirstLastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .HasColumnName("IdentityType")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("NumberIdentity")
                        .IsRequired()
                        .HasColumnName("NumberIdentity")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("SeconLastName")
                        .IsRequired()
                        .HasColumnName("SecondLastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnName("SecondName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("DeveloperId");

                    b.HasIndex("ContractId");

                    b.ToTable("Developer");
                });

            modelBuilder.Entity("GalaxyMiReto.GalaxyMiReto.Models.Developer", b =>
                {
                    b.HasOne("GalaxyMiReto.GalaxyMiReto.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContractId");
                });
#pragma warning restore 612, 618
        }
    }
}
